language: c
compiler:
    - gcc
    - clang
script: sudo apt-get install gdb libprotobuf-c0-dev protobuf-c-compiler uuid-dev && git submodule update --init && cmake .  && make && ./test/unit_test/run_tests
