/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: auth_joiner.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "auth_joiner.pb-c.h"
void   auth_joiner__init
                     (AuthJoiner         *message)
{
  static AuthJoiner init_value = AUTH_JOINER__INIT;
  *message = init_value;
}
size_t auth_joiner__get_packed_size
                     (const AuthJoiner *message)
{
  assert(message->base.descriptor == &auth_joiner__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t auth_joiner__pack
                     (const AuthJoiner *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &auth_joiner__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t auth_joiner__pack_to_buffer
                     (const AuthJoiner *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &auth_joiner__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AuthJoiner *
       auth_joiner__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AuthJoiner *)
     protobuf_c_message_unpack (&auth_joiner__descriptor,
                                allocator, len, data);
}
void   auth_joiner__free_unpacked
                     (AuthJoiner *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &auth_joiner__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor auth_joiner__field_descriptors[3] =
{
  {
    "session_guid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AuthJoiner, session_guid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "joiner_guid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AuthJoiner, joiner_guid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_requesting_join",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AuthJoiner, is_requesting_join),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned auth_joiner__field_indices_by_name[] = {
  2,   /* field[2] = is_requesting_join */
  1,   /* field[1] = joiner_guid */
  0,   /* field[0] = session_guid */
};
static const ProtobufCIntRange auth_joiner__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor auth_joiner__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "auth_joiner",
  "AuthJoiner",
  "AuthJoiner",
  "",
  sizeof(AuthJoiner),
  3,
  auth_joiner__field_descriptors,
  auth_joiner__field_indices_by_name,
  1,  auth_joiner__number_ranges,
  (ProtobufCMessageInit) auth_joiner__init,
  NULL,NULL,NULL    /* reserved[123] */
};
