/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: auth_joiner.proto */

#ifndef PROTOBUF_C_auth_5fjoiner_2eproto__INCLUDED
#define PROTOBUF_C_auth_5fjoiner_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1000002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _AuthJoiner AuthJoiner;


/* --- enums --- */


/* --- messages --- */

struct  _AuthJoiner
{
  ProtobufCMessage base;
  char *session_guid;
  char *joiner_guid;
  int32_t is_requesting_join;
};
#define AUTH_JOINER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&auth_joiner__descriptor) \
    , NULL, NULL, 0 }


/* AuthJoiner methods */
void   auth_joiner__init
                     (AuthJoiner         *message);
size_t auth_joiner__get_packed_size
                     (const AuthJoiner   *message);
size_t auth_joiner__pack
                     (const AuthJoiner   *message,
                      uint8_t             *out);
size_t auth_joiner__pack_to_buffer
                     (const AuthJoiner   *message,
                      ProtobufCBuffer     *buffer);
AuthJoiner *
       auth_joiner__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   auth_joiner__free_unpacked
                     (AuthJoiner *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*AuthJoiner_Closure)
                 (const AuthJoiner *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor auth_joiner__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_auth_5fjoiner_2eproto__INCLUDED */
